### ISSUE TITLE
Usage for custom CNN

### ISSUE THREAD

**Issue by anbai106** [InFoCusp/tf_cnnvis#39]
Hi,
Thanks for you work. I tried your example: `example/tf_cnnvis_Example1;ipynb`, it works well with AlexNet.

So I adapted this function `activation_visualization` with my own CNN architecture defined like this:

`Conv1_1+relu+conv1_2+relu+pool1+conv2_1+relu+conv2_2+relu+pool2+fc1`

The activation map was successfully saved for conv1_1 and conv1_2, but it gave error for conv2_1 at this function: 
`def _activation(graph, sess, op_tensor, feed_dict):
    with graph.as_default() as g:
        with sess.as_default() as sess:
            act = sess.run(op_tensor, feed_dict = feed_dict)
    return act`

The error from this: ` act = sess.run(op_tensor, feed_dict = feed_dict)`, I think it is the problem of the shapes for **op_tensor (?, 112, 112, 64) and feed_dict (?, 224, 224, 3).**. 

The error is: `InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_2' with dtype float`

As my CNN is slightly different with AlexNet, I did not use any local response normalization. So my question is, is your visualizer works for general CNN model or a specific architecture?

Thanks in advance

Look forward to your response.

Hao

**Comment by Liron42** [comment]
Hi Hao,
I'm trying to implement this on my own customer CNN as well (and I'm kind of new to TF in general), I would like to address you with some conflicts I had:
1. The API should be used after or DURING training of my net?
2.The placeholders listed here are proprietary placeholders for the tf.cnnvis that I need to define before calling the API or use the ones from the graph?

Thanks,

Liron

**Comment by anbai106** [comment]
@Liron42 
1) yer or no, you can of course visualize the activation map (for example) during the training with the updated weight of each layer, but the basic usage will focus on the well-trained weights. So I always visualize it after training. 

2) Yes, you should create a placeholder for the tensor representing each layer. Then you fit the placeholder with the real image.

**Comment by Liron42** [comment]
@anbai106 Thanks for the quick response.
Now I'm having trouble debugging this, I'm getting : 
"    Traceback (most recent call last):
  File "TrainInceptionV3.py", line 66, in <module>
    path_outdir='Output')
  File "/opt/anaconda3/lib/python3.6/site-packages/tf_cnnvis-1.0.0-py3.6.egg/tf_cnnvis/tf_cnnvis.py", line 410, in deconv_visualization
  File "/opt/anaconda3/lib/python3.6/site-packages/tf_cnnvis-1.0.0-py3.6.egg/tf_cnnvis/tf_cnnvis.py", line 169, in _get_visualization
  File "/opt/anaconda3/lib/python3.6/site-packages/tf_cnnvis-1.0.0-py3.6.egg/tf_cnnvis/tf_cnnvis.py", line 227, in _visualization_by_layer_type
  File "/opt/anaconda3/lib/python3.6/site-packages/tf_cnnvis-1.0.0-py3.6.egg/tf_cnnvis/tf_cnnvis.py", line 270, in _visualization_by_layer_name
  File "/opt/anaconda3/lib/python3.6/site-packages/tf_cnnvis-1.0.0-py3.6.egg/tf_cnnvis/utils.py", line 69, in parse_tensors_dict
IndexError: list index out of range"

Ideas? I can't tell whats exactly its complaining about - is it on my code? I verified the output dir (running all from the same folder).

Thanks!

**Comment by falaktheoptimist** [comment]
Hi!
Sorry for the late reply. But, the tool is very generalized and can be used on any netwrok of your creation. So, the first error you posted @anbai106  was probably because the shapes of the placeholder and the input you passed in were different. Your answer to question 1. by @Liron42  was correct. However, in response to question 2. You will need to have an input placeholder in your network where you pass in the input image. No other constraints on the network are in place. You will not require any other placeholders (They are not required for all layers). The Tensorboard page should display the outputs for the layers you need. There is an input field for specifying this -  it is named layers. You can pass the layers for which you want to see the visualization as a list. 

@Liron42 If you share the code or snippet, we might be able to debug better. The Traceback isn't very helpful in understanding the exact cause of error.
Thanks!

**Comment by falaktheoptimist** [comment]
Closing this for now. Reopen if needed.
