### ISSUE TITLE
About conv2d and conv2_1 

### ISSUE THREAD

**Issue by douhaoexia** [InFoCusp/tf_cnnvis#45]
Hello, thank you for your valuable work.
I have a doubt . 
I have run the example 1 and get the visiualization on the tensorboard.
What is the difference between the reconstructed feature conv2_1(or conv2_2) with the conv2d(conv2d_1--7) ?
I want to know where the feature conv2d(1--7) are from.
Look forward to your reply!

**Comment by falaktheoptimist** [comment]
We have reconstructions from all relu layers, all convolution layers and all pooling layers in that example. The conv2_1, conv2_2 are the reconstructions from the relu layers. This is because we have named the output of those tensors to that name. The other outputs conv2d_1, conv2d_2 and so on are from the reconstructions from the convolution layers. Here, we had not provided any names so Tf by default gives the names conv2d_n to all the convolution ops.

**Comment by douhaoexia** [comment]
Got it, thank you very much!
